// Home Library catalogue: one entry per book you own.
// To add a book, copy any line below, change the details, and keep the commas.
//   id         : a short unique name (lowercase, dashes). Never change it once set:
//                your reading notes are saved against it.
//   genre      : one of the GENRES listed below
//   shelf      : where the book physically sits (see SHELVES)
//   cover      : true when a cover image exists at covers/<id>.jpg
//   needsCheck : true if the title or author still needs confirming

window.SHELVES = {
  "A": "Dark cabinet, shelf 1",
  "B": "Dark cabinet, shelf 2",
  "C": "Wall alcove, top shelf",
  "D": "Wall alcove, middle shelf",
  "E": "Wall alcove, bottom shelf"
};

window.GENRES = [
  "Literary Fiction",
  "Popular Fiction",
  "Crime & Mystery",
  "Fantasy & Sci-Fi",
  "Short Stories & Myths",
  "Classics & Drama",
  "Biography & Memoir",
  "Music",
  "Sport",
  "Film & Media",
  "Books & Writing",
  "History",
  "Travel",
  "Politics & World Affairs",
  "Business & Money",
  "Science & Nature",
  "Mind & Self-help",
  "Food",
  "Reference & Other"
];

window.BOOKS = [
  {"id": "the-parrots-of-desire", "title": "The Parrots of Desire", "author": "Amrita Narayanan (ed.)", "genre": "Short Stories & Myths", "shelf": "A"},
  {"id": "colorful-notions", "title": "Colorful Notions", "author": "Mohit Goyal", "genre": "Popular Fiction", "shelf": "A"},
  {"id": "my-father-is-a-hero", "title": "My Father Is a Hero", "author": "Nishant Kaushik", "genre": "Popular Fiction", "shelf": "A"},
  {"id": "wottaplot", "title": "Wottaplot!", "author": "Santosh Vishwanath", "genre": "Popular Fiction", "shelf": "A"},
  {"id": "confused-bastards", "title": "Confused Bastards", "author": "Manav Vigg", "genre": "Popular Fiction", "shelf": "A"},
  {"id": "unlawful-justice", "title": "Unlawful Justice", "author": "Vish Dhamija", "genre": "Crime & Mystery", "shelf": "A"},
  {"id": "train-to-pakistan", "title": "Train to Pakistan", "author": "Khushwant Singh", "genre": "Literary Fiction", "shelf": "A"},
  {"id": "delhi", "title": "Delhi", "author": "Khushwant Singh", "genre": "Literary Fiction", "shelf": "A"},
  {"id": "indigo-sun", "title": "Indigo Sun", "author": "Rupa Bhullar", "genre": "Literary Fiction", "shelf": "A"},
  {"id": "maidless-in-mumbai", "title": "Maidless in Mumbai", "author": "Payal Kapadia", "genre": "Popular Fiction", "shelf": "A"},
  {"id": "rebound", "title": "Rebound", "author": "Sanil Sachar", "genre": "Popular Fiction", "shelf": "A"},
  {"id": "the-muddy-river", "title": "The Muddy River", "author": "P.A. Krishnan", "genre": "Literary Fiction", "shelf": "A"},
  {"id": "the-book-hunters-of-katpadi", "title": "The Book Hunters of Katpadi", "author": "Pradeep Sebastian", "genre": "Books & Writing", "shelf": "A"},
  {"id": "murder-with-bengali-characteristics", "title": "Murder with Bengali Characteristics", "author": "Shovon Chowdhury", "genre": "Crime & Mystery", "shelf": "A"},
  {"id": "jasoda", "title": "Jasoda", "author": "Kiran Nagarkar", "genre": "Literary Fiction", "shelf": "A"},
  {"id": "when-only-love-remains", "title": "When Only Love Remains", "author": "Durjoy Datta", "genre": "Popular Fiction", "shelf": "A"},
  {"id": "you-were-my-crush", "title": "You Were My Crush…", "author": "Durjoy Datta & Orvana Ghai", "genre": "Popular Fiction", "shelf": "A"},
  {"id": "hold-my-hand", "title": "Hold My Hand", "author": "Durjoy Datta", "genre": "Popular Fiction", "shelf": "A"},
  {"id": "till-the-last-breath", "title": "Till the Last Breath…", "author": "Durjoy Datta", "genre": "Popular Fiction", "shelf": "A"},
  {"id": "world-s-best-boyfriend", "title": "World's Best Boyfriend", "author": "Durjoy Datta", "genre": "Popular Fiction", "shelf": "A"},
  {"id": "the-shadow-lines", "title": "The Shadow Lines", "author": "Amitav Ghosh", "genre": "Literary Fiction", "shelf": "A"},
  {"id": "sea-of-poppies", "title": "Sea of Poppies", "author": "Amitav Ghosh", "genre": "Literary Fiction", "shelf": "A"},
  {"id": "felix-the-railway-cat", "title": "Felix the Railway Cat", "author": "Kate Moore", "genre": "Biography & Memoir", "shelf": "A"},
  {"id": "the-buddha-of-suburbia", "title": "The Buddha of Suburbia", "author": "Hanif Kureishi", "genre": "Literary Fiction", "shelf": "A"},
  {"id": "why-i-write", "title": "Why I Write", "author": "George Orwell", "genre": "Books & Writing", "shelf": "A"},
  {"id": "philip-k-dick-the-last-interview", "title": "Philip K. Dick: The Last Interview", "author": "Philip K. Dick", "genre": "Books & Writing", "shelf": "A"},
  {"id": "p-s-i-love-you", "title": "P.S. I Love You", "author": "Cecelia Ahern", "genre": "Popular Fiction", "shelf": "A"},
  {"id": "the-sense-of-an-ending", "title": "The Sense of an Ending", "author": "Julian Barnes", "genre": "Literary Fiction", "shelf": "A"},
  {"id": "the-reader", "title": "The Reader", "author": "Bernhard Schlink", "genre": "Literary Fiction", "shelf": "A"},
  {"id": "good-neighbors", "title": "Good Neighbors", "author": "Ryan David Jahn", "genre": "Crime & Mystery", "shelf": "A"},
  {"id": "the-forty-rules-of-love", "title": "The Forty Rules of Love", "author": "Elif Shafak", "genre": "Literary Fiction", "shelf": "A"},
  {"id": "one-hundred-years-of-solitude", "title": "One Hundred Years of Solitude", "author": "Gabriel García Márquez", "genre": "Literary Fiction", "shelf": "A"},
  {"id": "love-in-the-time-of-cholera", "title": "Love in the Time of Cholera", "author": "Gabriel García Márquez", "genre": "Literary Fiction", "shelf": "A"},
  {"id": "the-kite-runner", "title": "The Kite Runner", "author": "Khaled Hosseini", "genre": "Literary Fiction", "shelf": "A"},
  {"id": "and-the-mountains-echoed", "title": "And the Mountains Echoed", "author": "Khaled Hosseini", "genre": "Literary Fiction", "shelf": "A"},
  {"id": "salmon-fishing-in-the-yemen", "title": "Salmon Fishing in the Yemen", "author": "Paul Torday", "genre": "Literary Fiction", "shelf": "A"},
  {"id": "the-thief-lord", "title": "The Thief Lord", "author": "Cornelia Funke", "genre": "Fantasy & Sci-Fi", "shelf": "A"},
  {"id": "william-shakespeare-s-star-wars", "title": "William Shakespeare's Star Wars", "author": "Ian Doescher", "genre": "Fantasy & Sci-Fi", "shelf": "A"},
  {"id": "all-the-bright-places", "title": "All the Bright Places", "author": "Jennifer Niven", "genre": "Popular Fiction", "shelf": "A"},
  {"id": "ready-player-one", "title": "Ready Player One", "author": "Ernest Cline", "genre": "Fantasy & Sci-Fi", "shelf": "A"},
  {"id": "vango", "title": "Vango", "author": "Timothée de Fombelle", "genre": "Fantasy & Sci-Fi", "shelf": "A"},
  {"id": "a-long-petal-of-the-sea", "title": "A Long Petal of the Sea", "author": "Isabel Allende", "genre": "Literary Fiction", "shelf": "A"},
  {"id": "marvels-mysteries-of-the-mahabharata", "title": "Marvels & Mysteries of the Mahabharata", "author": "Abhijit Basu", "genre": "Short Stories & Myths", "shelf": "B"},
  {"id": "the-demon-seed-and-other-writings", "title": "The Demon Seed and Other Writings", "author": "M.T. Vasudevan Nair", "genre": "Short Stories & Myths", "shelf": "B"},
  {"id": "boo-13-stories-that-will-send-a-chill-down-your", "title": "Boo: 13 Stories That Will Send a Chill Down Your Spine", "author": "Shinie Antony (ed.)", "genre": "Short Stories & Myths", "shelf": "B"},
  {"id": "wise-and-otherwise", "title": "Wise and Otherwise", "author": "Sudha Murty", "genre": "Short Stories & Myths", "shelf": "B"},
  {"id": "something-happened-on-the-way-to-heaven", "title": "Something Happened on the Way to Heaven", "author": "Sudha Murty", "genre": "Short Stories & Myths", "shelf": "B"},
  {"id": "grandma-s-bag-of-stories", "title": "Grandma's Bag of Stories", "author": "Sudha Murty", "genre": "Short Stories & Myths", "shelf": "B"},
  {"id": "day-s-end-stories-life-after-sundown-in-small-to", "title": "Day's End Stories: Life After Sundown in Small-Town India", "author": "Subuhi Jiwani (ed.)", "genre": "Short Stories & Myths", "shelf": "B"},
  {"id": "rain-in-the-mountains", "title": "Rain in the Mountains", "author": "Ruskin Bond", "genre": "Short Stories & Myths", "shelf": "B"},
  {"id": "the-night-train-at-deoli", "title": "The Night Train at Deoli", "author": "Ruskin Bond", "genre": "Short Stories & Myths", "shelf": "B"},
  {"id": "rusty-the-boy-from-the-hills", "title": "Rusty, the Boy from the Hills", "author": "Ruskin Bond", "genre": "Short Stories & Myths", "shelf": "B"},
  {"id": "the-tiger-roars", "title": "The Tiger Roars", "author": "Kenneth Anderson", "genre": "Short Stories & Myths", "shelf": "B"},
  {"id": "great-indian-short-stories", "title": "Great Indian Short Stories", "author": "Anthology", "genre": "Short Stories & Myths", "shelf": "B"},
  {"id": "lore-of-the-land", "title": "Lore of the Land", "author": "Nalini Ramachandran", "genre": "Short Stories & Myths", "shelf": "B"},
  {"id": "a-clutch-of-indian-masterpieces", "title": "A Clutch of Indian Masterpieces", "author": "David Davidar (ed.)", "genre": "Short Stories & Myths", "shelf": "B"},
  {"id": "the-tamil-story-through-the-times-through-the-ti", "title": "The Tamil Story: Through the Times, Through the Tides", "author": "Dilip Kumar (ed.), tr. Subashree Krishnaswamy", "genre": "Short Stories & Myths", "shelf": "B"},
  {"id": "an-inky-parade-tales-for-bibliophiles", "title": "An Inky Parade: Tales for Bibliophiles", "author": "Pradeep Sebastian", "genre": "Books & Writing", "shelf": "B"},
  {"id": "a-3rd-serving-of-chicken-soup-for-the-soul", "title": "A 3rd Serving of Chicken Soup for the Soul", "author": "Jack Canfield & Mark Victor Hansen", "genre": "Short Stories & Myths", "shelf": "B"},
  {"id": "past-perfect-present-tense", "title": "Past Perfect, Present Tense", "author": "Richard Peck", "genre": "Short Stories & Myths", "shelf": "B"},
  {"id": "classic-detective-stories", "title": "Classic Detective Stories", "author": "Anthology", "genre": "Crime & Mystery", "shelf": "B"},
  {"id": "the-casebook-of-sherlock-holmes", "title": "The Casebook of Sherlock Holmes", "author": "Arthur Conan Doyle", "genre": "Crime & Mystery", "shelf": "B"},
  {"id": "tales-of-terror", "title": "Tales of Terror", "author": "", "genre": "Short Stories & Myths", "shelf": "B", "needsCheck": true},
  {"id": "100-selected-stories", "title": "100 Selected Stories", "author": "O. Henry", "genre": "Short Stories & Myths", "shelf": "B"},
  {"id": "the-day-of-silence-and-other-stories", "title": "The Day of Silence and Other Stories", "author": "George Gissing", "genre": "Short Stories & Myths", "shelf": "B"},
  {"id": "great-stories-by-nobel-prize-winners", "title": "Great Stories by Nobel Prize Winners", "author": "Leo Hamalian & Edmond L. Volpe (eds.)", "genre": "Short Stories & Myths", "shelf": "B"},
  {"id": "the-penguin-book-of-modern-women-s-short-stories", "title": "The Penguin Book of Modern Women's Short Stories", "author": "Anthology", "genre": "Short Stories & Myths", "shelf": "B"},
  {"id": "21-tales-to-tell", "title": "21 Tales to Tell", "author": "Various authors", "genre": "Short Stories & Myths", "shelf": "B"},
  {"id": "the-moth-all-these-wonders", "title": "The Moth: All These Wonders", "author": "The Moth", "genre": "Short Stories & Myths", "shelf": "B"},
  {"id": "true-crime", "title": "True Crime", "author": "Jonathan Goodman (ed.)", "genre": "Crime & Mystery", "shelf": "B"},
  {"id": "the-giant-book-of-private-eye-stories", "title": "The Giant Book of Private Eye Stories", "author": "Bill Pronzini & Martin H. Greenberg (eds.)", "genre": "Crime & Mystery", "shelf": "B"},
  {"id": "the-complete-sherlock-holmes", "title": "The Complete Sherlock Holmes", "author": "Arthur Conan Doyle", "genre": "Crime & Mystery", "shelf": "B"},
  {"id": "the-beat-goes-on", "title": "The Beat Goes On", "author": "Ian Rankin", "genre": "Crime & Mystery", "shelf": "B"},
  {"id": "candide-zadig-and-selected-stories", "title": "Candide, Zadig and Selected Stories", "author": "Voltaire", "genre": "Classics & Drama", "shelf": "B"},
  {"id": "the-major-plays", "title": "The Major Plays", "author": "Anton Chekhov", "genre": "Classics & Drama", "shelf": "B"},
  {"id": "famous-american-plays-of-the-20th-21st-century", "title": "Famous American Plays of the 20th/21st Century", "author": "Anthology", "genre": "Classics & Drama", "shelf": "B"},
  {"id": "50-great-oriental-stories", "title": "50 Great Oriental Stories", "author": "Anthology", "genre": "Short Stories & Myths", "shelf": "B"},
  {"id": "the-complete-works-of-oscar-wilde", "title": "The Complete Works of Oscar Wilde", "author": "Oscar Wilde", "genre": "Classics & Drama", "shelf": "B"},
  {"id": "world-drama", "title": "World Drama", "author": "Anthology", "genre": "Classics & Drama", "shelf": "B"},
  {"id": "reader-s-digest-select-editions-where-the-shadow", "title": "Reader's Digest Select Editions — Where the Shadows Lie / Blood Lines / The Mountain Between Us / Rainwater", "author": "Various", "genre": "Popular Fiction", "shelf": "B"},
  {"id": "reader-s-digest-select-editions-the-distant-echo", "title": "Reader's Digest Select Editions — The Distant Echo / Trojan Odyssey / Leaving Eden / Blood Is the Sky", "author": "Various", "genre": "Popular Fiction", "shelf": "B"},
  {"id": "reader-s-digest-select-editions-the-scarecrow-ha", "title": "Reader's Digest Select Editions — The Scarecrow / Half Broke Horses / Thirteen Hours / From Cradle to Grave", "author": "Various", "genre": "Popular Fiction", "shelf": "B"},
  {"id": "reader-s-digest-select-editions-the-da-vinci-cod", "title": "Reader's Digest Select Editions — The Da Vinci Code / Up and Down in the Dales / The Return of the Dancing Master / Gathering Light", "author": "Various", "genre": "Popular Fiction", "shelf": "B"},
  {"id": "reader-s-digest-select-editions-the-king-of-tort", "title": "Reader's Digest Select Editions — The King of Torts / A Week in Winter / The Last Detective / Eat Cake", "author": "Various", "genre": "Popular Fiction", "shelf": "B"},
  {"id": "reader-s-digest-select-editions-inspector-singh", "title": "Reader's Digest Select Editions — Inspector Singh Investigates / Lifeguard / The Poacher's Son", "author": "Various", "genre": "Popular Fiction", "shelf": "B", "needsCheck": true},
  {"id": "we-could-be-bowie-and-his-heroes", "title": "We Could Be… Bowie and His Heroes", "author": "", "genre": "Music", "shelf": "C", "needsCheck": true},
  {"id": "the-elephant-chaser-s-daughter", "title": "The Elephant Chaser's Daughter", "author": "Shilpa Raj", "genre": "Biography & Memoir", "shelf": "C"},
  {"id": "swami-vivekanandar", "title": "Swami Vivekanandar", "author": "", "genre": "Biography & Memoir", "shelf": "C", "language": "Tamil"},
  {"id": "beyond-the-last-blue-mountain", "title": "Beyond the Last Blue Mountain", "author": "R.M. Lala", "genre": "Biography & Memoir", "shelf": "C"},
  {"id": "why-i-failed", "title": "Why I Failed", "author": "Shweta Punj", "genre": "Business & Money", "shelf": "C"},
  {"id": "the-wave-rider", "title": "The Wave Rider", "author": "Ajit Balakrishnan", "genre": "Business & Money", "shelf": "C"},
  {"id": "bhujia-barons", "title": "Bhujia Barons", "author": "Pavitra Kumar", "genre": "Business & Money", "shelf": "C"},
  {"id": "teenage-ceos", "title": "Teenage CEOs", "author": "Ganesh V.", "genre": "Business & Money", "shelf": "C"},
  {"id": "young-turks", "title": "Young Turks", "author": "Shereen Bhan & Syna Dehnugara", "genre": "Business & Money", "shelf": "C"},
  {"id": "the-tcs-story-and-beyond", "title": "The TCS Story… and Beyond", "author": "S. Ramadorai", "genre": "Business & Money", "shelf": "C"},
  {"id": "don-t-fall-off-the-mountain", "title": "Don't Fall Off the Mountain", "author": "Shirley MacLaine", "genre": "Biography & Memoir", "shelf": "C"},
  {"id": "the-brave-param-vir-chakra-stories", "title": "The Brave: Param Vir Chakra Stories", "author": "Rachna Bisht Rawat", "genre": "History", "shelf": "C"},
  {"id": "after-the-applause", "title": "After the Applause", "author": "Charles Wilkins with Gordie & Colleen Howe", "genre": "Sport", "shelf": "C"},
  {"id": "scenes-from-a-writer-s-life", "title": "Scenes from a Writer's Life", "author": "Ruskin Bond", "genre": "Books & Writing", "shelf": "C"},
  {"id": "spy-princess-the-life-of-noor-inayat-khan", "title": "Spy Princess: The Life of Noor Inayat Khan", "author": "Shrabani Basu", "genre": "Biography & Memoir", "shelf": "C"},
  {"id": "the-snowball-warren-buffett-and-the-business-of", "title": "The Snowball: Warren Buffett and the Business of Life", "author": "Alice Schroeder", "genre": "Business & Money", "shelf": "C"},
  {"id": "mr-shankly-s-photograph", "title": "Mr Shankly's Photograph", "author": "Stephen F. Kelly", "genre": "Sport", "shelf": "C"},
  {"id": "karmayogi-a-biography-of-e-sreedharan", "title": "Karmayogi: A Biography of E. Sreedharan", "author": "M.S. Ashokan", "genre": "Biography & Memoir", "shelf": "C"},
  {"id": "into-the-wild", "title": "Into the Wild", "author": "Jon Krakauer", "genre": "Biography & Memoir", "shelf": "C"},
  {"id": "super-30", "title": "Super 30", "author": "Anand Kumar", "genre": "Biography & Memoir", "shelf": "C"},
  {"id": "my-name-escapes-me", "title": "My Name Escapes Me", "author": "Alec Guinness", "genre": "Film & Media", "shelf": "C"},
  {"id": "chronicles", "title": "Chronicles", "author": "Bob Dylan", "genre": "Music", "shelf": "C"},
  {"id": "princess", "title": "Princess", "author": "Jean Sasson", "genre": "Biography & Memoir", "shelf": "C"},
  {"id": "the-noodle-maker-of-kalimpong", "title": "The Noodle Maker of Kalimpong", "author": "Gyalo Thondup & Anne F. Thurston", "genre": "Biography & Memoir", "shelf": "C"},
  {"id": "the-dhoni-touch", "title": "The Dhoni Touch", "author": "Bharat Sundaresan", "genre": "Sport", "shelf": "C"},
  {"id": "lights-out", "title": "Lights Out", "author": "L. Subramani", "genre": "Sport", "shelf": "C"},
  {"id": "an-autobiography-or-the-story-of-my-experiments", "title": "An Autobiography, or The Story of My Experiments with Truth", "author": "M.K. Gandhi", "genre": "Biography & Memoir", "shelf": "C"},
  {"id": "fever-pitch", "title": "Fever Pitch", "author": "Nick Hornby", "genre": "Sport", "shelf": "C"},
  {"id": "cricket-s-great-entertainers", "title": "Cricket's Great Entertainers", "author": "Henry Blofeld", "genre": "Sport", "shelf": "C"},
  {"id": "room-full-of-mirrors-a-biography-of-jimi-hendrix", "title": "Room Full of Mirrors: A Biography of Jimi Hendrix", "author": "Charles R. Cross", "genre": "Music", "shelf": "C"},
  {"id": "rat-pack-confidential", "title": "Rat Pack Confidential", "author": "Shawn Levy", "genre": "Music", "shelf": "C"},
  {"id": "the-last-lecture", "title": "The Last Lecture", "author": "Randy Pausch", "genre": "Biography & Memoir", "shelf": "C"},
  {"id": "mcqueen", "title": "McQueen", "author": "Christopher Sandford", "genre": "Film & Media", "shelf": "C"},
  {"id": "when-the-levee-breaks-the-making-of-led-zeppelin", "title": "When the Levee Breaks: The Making of Led Zeppelin IV", "author": "Andy Fyfe", "genre": "Music", "shelf": "C"},
  {"id": "shadows-in-the-sun", "title": "Shadows in the Sun", "author": "Gayathri Ramprasad", "genre": "Biography & Memoir", "shelf": "C"},
  {"id": "mgr-a-life", "title": "MGR: A Life", "author": "R. Kannan", "genre": "Biography & Memoir", "shelf": "C"},
  {"id": "nobel-laureates", "title": "Nobel Laureates", "author": "", "genre": "Reference & Other", "shelf": "C", "needsCheck": true},
  {"id": "one-life-is-not-enough", "title": "One Life Is Not Enough", "author": "K. Natwar Singh", "genre": "Biography & Memoir", "shelf": "C"},
  {"id": "raj-kapoor", "title": "Raj Kapoor", "author": "Ritu Nanda", "genre": "Film & Media", "shelf": "C"},
  {"id": "karunanidhi", "title": "Karunanidhi", "author": "Sandhya Ravishankar", "genre": "Biography & Memoir", "shelf": "C"},
  {"id": "ashoka-the-great", "title": "Ashoka the Great", "author": "Wytze Keuning", "genre": "History", "shelf": "C"},
  {"id": "of-gifted-voice", "title": "Of Gifted Voice", "author": "Keshav Desiraju", "genre": "Music", "shelf": "C"},
  {"id": "makkal-thalaivi-j-jayalalithaa", "title": "Makkal Thalaivi J. Jayalalithaa", "author": "", "genre": "Biography & Memoir", "shelf": "C", "language": "Tamil"},
  {"id": "saint-tiruvalluvar", "title": "Saint Tiruvalluvar", "author": "", "genre": "Biography & Memoir", "shelf": "C"},
  {"id": "vaathiyaar-mgr-in-vaazhkai", "title": "Vaathiyaar: MGR-in Vaazhkai", "author": "R. Muthukumar", "genre": "Biography & Memoir", "shelf": "C", "language": "Tamil"},
  {"id": "the-innovators", "title": "The Innovators", "author": "Walter Isaacson", "genre": "Business & Money", "shelf": "C"},
  {"id": "hello-goodbye-hello", "title": "Hello Goodbye Hello", "author": "Craig Brown", "genre": "Biography & Memoir", "shelf": "C"},
  {"id": "the-secret-diary-of-kasturba", "title": "The Secret Diary of Kasturba", "author": "Neelima Dalmia Adhar", "genre": "Literary Fiction", "shelf": "C"},
  {"id": "the-accidental-prime-minister", "title": "The Accidental Prime Minister", "author": "Sanjaya Baru", "genre": "Politics & World Affairs", "shelf": "C"},
  {"id": "the-library-a-fragile-history", "title": "The Library: A Fragile History", "author": "Andrew Pettegree & Arthur der Weduwen", "genre": "Books & Writing", "shelf": "D"},
  {"id": "say-what-happened-a-story-of-documentaries", "title": "Say What Happened: A Story of Documentaries", "author": "Nick Fraser", "genre": "Film & Media", "shelf": "D"},
  {"id": "through-the-eyes-of-a-cinematographer-a-biograph", "title": "Through the Eyes of a Cinematographer: A Biography of Soumendu Roy", "author": "Devapriya Sanyal", "genre": "Film & Media", "shelf": "D"},
  {"id": "horribly-awkward", "title": "Horribly Awkward", "author": "Edwin Page", "genre": "Film & Media", "shelf": "D"},
  {"id": "speaking-of-films", "title": "Speaking of Films", "author": "Satyajit Ray", "genre": "Film & Media", "shelf": "D"},
  {"id": "the-anatomy-of-genres", "title": "The Anatomy of Genres", "author": "John Truby", "genre": "Film & Media", "shelf": "D"},
  {"id": "reel-india", "title": "Reel India", "author": "Namrata Joshi", "genre": "Film & Media", "shelf": "D"},
  {"id": "screenplay-the-foundations-of-screenwriting", "title": "Screenplay: The Foundations of Screenwriting", "author": "Syd Field", "genre": "Film & Media", "shelf": "D"},
  {"id": "housefull-the-golden-age-of-hindi-cinema", "title": "Housefull: The Golden Age of Hindi Cinema", "author": "Ziya Us Salam (ed.)", "genre": "Film & Media", "shelf": "D"},
  {"id": "the-art-and-business-of-cinema", "title": "The Art and Business of Cinema", "author": "G. Dhananjayan", "genre": "Film & Media", "shelf": "D"},
  {"id": "satyajit-ray", "title": "Satyajit Ray", "author": "Bhaskar Chattopadhyay", "genre": "Film & Media", "shelf": "D"},
  {"id": "an-actor-prepares", "title": "An Actor Prepares", "author": "Constantin Stanislavski", "genre": "Film & Media", "shelf": "D"},
  {"id": "making-short-films", "title": "Making Short Films", "author": "Clifford Thurlow", "genre": "Film & Media", "shelf": "D"},
  {"id": "jerusalem-the-biography", "title": "Jerusalem: The Biography", "author": "Simon Sebag Montefiore", "genre": "History", "shelf": "D"},
  {"id": "letters-from-a-lost-generation", "title": "Letters from a Lost Generation", "author": "Alan Bishop & Mark Bostridge (eds.)", "genre": "History", "shelf": "D"},
  {"id": "meeting-the-enemy", "title": "Meeting the Enemy", "author": "Richard van Emden", "genre": "History", "shelf": "D"},
  {"id": "the-book-of-books", "title": "The Book of Books", "author": "Melvyn Bragg", "genre": "Books & Writing", "shelf": "D"},
  {"id": "krakatoa", "title": "Krakatoa", "author": "Simon Winchester", "genre": "History", "shelf": "D"},
  {"id": "inside-the-box-my-life-with-test-match-special", "title": "Inside the Box: My Life with Test Match Special", "author": "Peter Baxter", "genre": "Sport", "shelf": "D"},
  {"id": "stiff-upper-lips-and-baggy-green-caps", "title": "Stiff Upper Lips and Baggy Green Caps", "author": "Simon Briggs", "genre": "Sport", "shelf": "D"},
  {"id": "and-now-on-radio-4", "title": "And Now on Radio 4", "author": "Simon Elmes", "genre": "Film & Media", "shelf": "D"},
  {"id": "captives-britain-empire-and-the-world-1600-1850", "title": "Captives: Britain, Empire and the World 1600–1850", "author": "Linda Colley", "genre": "History", "shelf": "D"},
  {"id": "nonfiction-ii", "title": "Nonfiction II", "author": "", "genre": "Reference & Other", "shelf": "D"},
  {"id": "o-jerusalem", "title": "O Jerusalem!", "author": "Dominique Lapierre & Larry Collins", "genre": "History", "shelf": "D"},
  {"id": "mao-s-great-famine", "title": "Mao's Great Famine", "author": "Frank Dikötter", "genre": "History", "shelf": "D"},
  {"id": "a-brief-history-of-video-games", "title": "A Brief History of Video Games", "author": "Richard Stanton", "genre": "Film & Media", "shelf": "D"},
  {"id": "interesting-times", "title": "Interesting Times", "author": "Eric Hobsbawm", "genre": "Biography & Memoir", "shelf": "D"},
  {"id": "notes-from-a-big-country", "title": "Notes from a Big Country", "author": "Bill Bryson", "genre": "Travel", "shelf": "D"},
  {"id": "the-opium-war", "title": "The Opium War", "author": "Julia Lovell", "genre": "History", "shelf": "D"},
  {"id": "the-subterranean-railway", "title": "The Subterranean Railway", "author": "Christian Wolmar", "genre": "History", "shelf": "D"},
  {"id": "great-australian-railway-stories", "title": "Great Australian Railway Stories", "author": "Bill 'Swampy' Marsh", "genre": "Travel", "shelf": "D"},
  {"id": "the-great-derangement", "title": "The Great Derangement", "author": "Amitav Ghosh", "genre": "Politics & World Affairs", "shelf": "D"},
  {"id": "our-sacred-land-voices-of-the-israeli-palestine", "title": "Our Sacred Land: Voices of the Israeli-Palestine Conflict", "author": "Kenizé Mourad (ed.)", "genre": "Politics & World Affairs", "shelf": "D"},
  {"id": "this-divided-island", "title": "This Divided Island", "author": "Samanth Subramanian", "genre": "Politics & World Affairs", "shelf": "D"},
  {"id": "perilous-interventions", "title": "Perilous Interventions", "author": "Hardeep Singh Puri", "genre": "Politics & World Affairs", "shelf": "D"},
  {"id": "the-isis-caliphate", "title": "The ISIS Caliphate", "author": "Stanly Johny", "genre": "Politics & World Affairs", "shelf": "D"},
  {"id": "amazons", "title": "Amazons", "author": "John Man", "genre": "History", "shelf": "D"},
  {"id": "the-beatles-10-years-that-shook-the-world", "title": "The Beatles: 10 Years That Shook the World", "author": "DK / Mojo", "genre": "Music", "shelf": "D"},
  {"id": "daring-to-win-our-special-forces-at-war", "title": "Daring to Win: Our Special Forces at War", "author": "David Eshel", "genre": "History", "shelf": "D"},
  {"id": "the-european-economy-since-1945", "title": "The European Economy Since 1945", "author": "Barry Eichengreen", "genre": "Business & Money", "shelf": "D"},
  {"id": "downsize-this", "title": "Downsize This!", "author": "Michael Moore", "genre": "Politics & World Affairs", "shelf": "D"},
  {"id": "roadrunner", "title": "Roadrunner", "author": "Dilip D'Souza", "genre": "Travel", "shelf": "D"},
  {"id": "dragon-on-our-doorstep", "title": "Dragon on Our Doorstep", "author": "Pravin Sawhney & Ghazala Wahab", "genre": "Politics & World Affairs", "shelf": "D"},
  {"id": "breakout-nations", "title": "Breakout Nations", "author": "Ruchir Sharma", "genre": "Business & Money", "shelf": "D"},
  {"id": "reimagining-pakistan", "title": "Reimagining Pakistan", "author": "Husain Haqqani", "genre": "Politics & World Affairs", "shelf": "D"},
  {"id": "the-big-connect", "title": "The Big Connect", "author": "Shaili Chopra", "genre": "Business & Money", "shelf": "D"},
  {"id": "the-ocean-of-churn", "title": "The Ocean of Churn", "author": "Sanjeev Sanyal", "genre": "History", "shelf": "D"},
  {"id": "a-world-of-three-zeros", "title": "A World of Three Zeros", "author": "Muhammad Yunus", "genre": "Business & Money", "shelf": "D"},
  {"id": "resource-wars-mapping-global-greed", "title": "Resource Wars: Mapping Global Greed", "author": "Bane Singh", "genre": "Politics & World Affairs", "shelf": "D"},
  {"id": "indus-divided", "title": "Indus Divided", "author": "Daniel Haines", "genre": "Politics & World Affairs", "shelf": "D"},
  {"id": "the-fate-of-food", "title": "The Fate of Food", "author": "Amanda Little", "genre": "Food", "shelf": "D"},
  {"id": "masala-lab", "title": "Masala Lab", "author": "Krish Ashok", "genre": "Food", "shelf": "D"},
  {"id": "the-flavour-of-spice", "title": "The Flavour of Spice", "author": "Marryam H. Reshii", "genre": "Food", "shelf": "D"},
  {"id": "secrets-of-health-from-the-indian-kitchen", "title": "Secrets of Health from the Indian Kitchen", "author": "Ratna Rajaiah", "genre": "Food", "shelf": "D"},
  {"id": "southern-flavours", "title": "Southern Flavours", "author": "Chandra Padmanabhan", "genre": "Food", "shelf": "D"},
  {"id": "bulls-bears-and-other-beasts", "title": "Bulls, Bears and Other Beasts", "author": "Santosh Nair", "genre": "Business & Money", "shelf": "D"},
  {"id": "everything-you-wanted-to-know-about-stock-market", "title": "Everything You Wanted to Know About Stock Market Investing", "author": "", "genre": "Business & Money", "shelf": "D"},
  {"id": "everything-you-wanted-to-know-about-investing-in", "title": "Everything You Wanted to Know About Investing in Mutual Funds", "author": "", "genre": "Business & Money", "shelf": "D"},
  {"id": "inside-the-investments-of-warren-buffett", "title": "Inside the Investments of Warren Buffett", "author": "Yefei Lu", "genre": "Business & Money", "shelf": "D"},
  {"id": "30-careers-that-will-power-2030", "title": "30 Careers That Will Power 2030", "author": "", "genre": "Business & Money", "shelf": "D"},
  {"id": "the-big-book-of-stress-relief-games", "title": "The Big Book of Stress Relief Games", "author": "Epstein", "genre": "Mind & Self-help", "shelf": "D"},
  {"id": "birds-and-birdsong", "title": "Birds and Birdsong", "author": "M. Krishnan", "genre": "Science & Nature", "shelf": "E"},
  {"id": "shades-of-shadows", "title": "Shades of Shadows", "author": "", "genre": "Reference & Other", "shelf": "E"},
  {"id": "how-to-be-a-writer", "title": "How to Be a Writer", "author": "Ruskin Bond", "genre": "Books & Writing", "shelf": "E"},
  {"id": "why-politics-fails", "title": "Why Politics Fails", "author": "Ben Ansell", "genre": "Politics & World Affairs", "shelf": "E"},
  {"id": "legacy-letters-from-eminent-parents-to-their-dau", "title": "Legacy: Letters from Eminent Parents to Their Daughters", "author": "Sudha Menon", "genre": "Mind & Self-help", "shelf": "E"},
  {"id": "how-to-talk-so-kids-will-listen-listen-so-kids-w", "title": "How to Talk So Kids Will Listen & Listen So Kids Will Talk", "author": "Adele Faber & Elaine Mazlish", "genre": "Mind & Self-help", "shelf": "E"},
  {"id": "how-to-talk-second-book-in-the-series", "title": "How to Talk… (second book in the series)", "author": "Adele Faber & Elaine Mazlish", "genre": "Mind & Self-help", "shelf": "E"},
  {"id": "stop-reading-the-news", "title": "Stop Reading the News", "author": "Rolf Dobelli", "genre": "Mind & Self-help", "shelf": "E"},
  {"id": "the-memory-book", "title": "The Memory Book", "author": "Harry Lorayne & Jerry Lucas", "genre": "Mind & Self-help", "shelf": "E"},
  {"id": "the-secret-lives-of-colour", "title": "The Secret Lives of Colour", "author": "Kassia St Clair", "genre": "History", "shelf": "E"},
  {"id": "the-arts-in-the-middle-ages-and-the-renaissance", "title": "The Arts in the Middle Ages and the Renaissance", "author": "Paul Lacroix", "genre": "History", "shelf": "E"},
  {"id": "manorama-yearbook-2024", "title": "Manorama Yearbook 2024", "author": "", "genre": "Reference & Other", "shelf": "E"},
  {"id": "their-name-is-today", "title": "Their Name Is Today", "author": "Johann Christoph Arnold", "genre": "Mind & Self-help", "shelf": "E"},
  {"id": "predictably-irrational", "title": "Predictably Irrational", "author": "Dan Ariely", "genre": "Mind & Self-help", "shelf": "E"},
  {"id": "the-cloudspotter-s-guide", "title": "The Cloudspotter's Guide", "author": "Gavin Pretor-Pinney", "genre": "Science & Nature", "shelf": "E"},
  {"id": "what-if", "title": "What If?", "author": "Randall Munroe", "genre": "Science & Nature", "shelf": "E"},
  {"id": "the-hidden-life-of-trees", "title": "The Hidden Life of Trees", "author": "Peter Wohlleben", "genre": "Science & Nature", "shelf": "E"},
  {"id": "interviews-from-the-ark", "title": "Interviews from the Ark", "author": "", "genre": "Science & Nature", "shelf": "E"},
  {"id": "for-the-love-of-physics", "title": "For the Love of Physics", "author": "Walter Lewin", "genre": "Science & Nature", "shelf": "E"},
  {"id": "management-say-it-with-fun", "title": "Management: Say It with Fun", "author": "Gopalan & K. Natarajan", "genre": "Business & Money", "shelf": "E"},
  {"id": "how-to-get-from-where-you-are-to-where-you-want", "title": "How to Get from Where You Are to Where You Want to Be", "author": "Jack Canfield", "genre": "Mind & Self-help", "shelf": "E"},
  {"id": "ready-study-go", "title": "Ready, Study, Go!", "author": "Khursheed Batliwala & Dinesh Ghodke", "genre": "Mind & Self-help", "shelf": "E"},
  {"id": "the-tell-tale-brain", "title": "The Tell-Tale Brain", "author": "V.S. Ramachandran", "genre": "Science & Nature", "shelf": "E"},
  {"id": "how-will-you-measure-your-life", "title": "How Will You Measure Your Life?", "author": "Clayton M. Christensen", "genre": "Mind & Self-help", "shelf": "E"},
  {"id": "social-intelligence", "title": "Social Intelligence", "author": "Daniel Goleman", "genre": "Mind & Self-help", "shelf": "E"},
  {"id": "the-power-of-habit", "title": "The Power of Habit", "author": "Charles Duhigg", "genre": "Mind & Self-help", "shelf": "E"},
  {"id": "thinking-fast-and-slow", "title": "Thinking, Fast and Slow", "author": "Daniel Kahneman", "genre": "Mind & Self-help", "shelf": "E"},
  {"id": "mastery", "title": "Mastery", "author": "Robert Greene", "genre": "Mind & Self-help", "shelf": "E"},
  {"id": "communication-skills", "title": "Communication Skills", "author": "", "genre": "Mind & Self-help", "shelf": "E"},
  {"id": "never-stop-learning", "title": "Never Stop Learning", "author": "Bradley R. Staats", "genre": "Mind & Self-help", "shelf": "E"},
  {"id": "opportunity-knocks-2-copies", "title": "Opportunity Knocks (2 copies)", "author": "", "genre": "Business & Money", "shelf": "E"},
  {"id": "success-recipe-2-copies", "title": "Success Recipe (2 copies)", "author": "Brian Tracy & Surendran J", "genre": "Business & Money", "shelf": "E"},
  {"id": "building-a-second-brain", "title": "Building a Second Brain", "author": "Tiago Forte", "genre": "Mind & Self-help", "shelf": "E"},
  {"id": "ted-talks-the-official-ted-guide-to-public-speak", "title": "TED Talks: The Official TED Guide to Public Speaking", "author": "Chris Anderson", "genre": "Mind & Self-help", "shelf": "E"},
  {"id": "very-good-lives", "title": "Very Good Lives", "author": "J.K. Rowling", "genre": "Mind & Self-help", "shelf": "E"},
  {"id": "the-checklist-manifesto", "title": "The Checklist Manifesto", "author": "Atul Gawande", "genre": "Mind & Self-help", "shelf": "E"},
  {"id": "born-to-win", "title": "Born to Win", "author": "", "genre": "Mind & Self-help", "shelf": "E"},
  {"id": "the-ant-and-the-elephant", "title": "The Ant and the Elephant", "author": "Vince Poscente", "genre": "Mind & Self-help", "shelf": "E"},
  {"id": "motivation-and-leadership-at-work", "title": "Motivation and Leadership at Work", "author": "Steers, Porter & Bigley", "genre": "Business & Money", "shelf": "E", "needsCheck": true},
  {"id": "formulae-and-definitions-in-chemistry", "title": "Formulae and Definitions in Chemistry", "author": "", "genre": "Reference & Other", "shelf": "E"},
];
